COS301-SE-2021/GeoCode

backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Controller/LeaderboardController.java, backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Model/Leaderboard.java, backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Repository/LeaderboardRepository.java, backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Request/CreateLeaderboardRequest.java, backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Response/CreateLeaderboardResponse.java, backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Service/LeaderboardService.java, backend/src/main/java/tech/geocodeapp/geocode/Leaderboard/Service/LeaderboardServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Controller/NotificationsController.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Model/Notifications.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Repository/NotificationsRepository.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Request/CreateNotificationsRequest.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Response/CreateNotificationsResponse.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Service/NotificationsService.java, backend/src/main/java/tech/geocodeapp/geocode/Notifications/Service/NotificationsServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Controller/TrackableController.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Model/Trackable.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Repository/TrackableRepository.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Request/CreateTrackableRequest.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Response/CreateTrackableResponse.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Service/TrackableService.java, backend/src/main/java/tech/geocodeapp/geocode/Trackable/Service/TrackableServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/User/Controller/UserController.java, backend/src/main/java/tech/geocodeapp/geocode/User/Service/UserInterfaceService/UserService.java, backend/src/main/java/tech/geocodeapp/geocode/User/Service/UserInterfaceServiceImpl/UserServiceImpl.java
Merge the updated file structure into the branch
=> Merge the updated file structure

.github/workflows/maven.yml, README.md, backend/pom.xml, backend/src/test/java/tech/geocodeapp/geocode/Collectable/CollectableMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/Collectable/CollectableServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/Collectable/CollectableSetMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/Collectable/CollectableTypeMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/GeoCode/GeoCodeMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/GeoCode/GeoCodeServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/GeocodeApplicationTests.java
Updated the subsystem code after demo one.
=> Updated Subsystem Code

.github/workflows/deploy.yml, .travis.yml, README.md, backend/pom.xml
Get the updates for the actions needed
=> Action Update

README.md, backend/pom.xml, backend/src/main/java/io/swagger/api/GeoCodeApiController.java, backend/src/main/java/io/swagger/model/GeoCode.java, backend/src/main/java/io/swagger/model/GetGeoCodesByDifficultyRequest.java, backend/src/main/java/io/swagger/model/GetGeoCodesByDifficultyResponse.java, backend/src/main/java/io/swagger/model/GetHintsRequest.java, backend/src/main/java/io/swagger/model/GetHintsResponse.java, backend/src/main/java/io/swagger/model/SwapCollectablesRequest.java, backend/src/main/java/io/swagger/model/SwapCollectablesResponse.java, backend/src/main/java/io/swagger/model/UpdateAvailabilityRequest.java, backend/src/main/java/io/swagger/model/UpdateAvailabilityResponse.java, backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Service/GeoCodeService.java, backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Service/GeoCodeServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/GeocodeApplication.java, backend/src/test/java/tech/geocodeapp/geocode/GeoCode/GeoCodeMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/GeoCode/GeoCodeServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/GeoCode/GeoCodeServiceImplTest.java, swagger.yaml
Updated the Requests and Response for GeoCode's swagger
=> Updated Swagger GeoCode 

backend/src/main/java/tech/geocodeapp/geocode/Collectable/Manager/CollectableTypeManager.java, backend/src/main/java/tech/geocodeapp/geocode/Collectable/Response/CreateCollectableTypeResponse.java, backend/src/main/java/tech/geocodeapp/geocode/Collectable/Service/CollectableServiceImpl.java
Added check for a null value properties HashMap in the CollectableTypeManager class.
=> Fix checking properties HashMap

backend/src/main/java/io/swagger/model/Collectable.java, backend/src/main/java/io/swagger/model/CollectableSet.java, backend/src/main/java/io/swagger/model/CollectableType.java
Fixed UUID generation to allow testing and adding to the database
=> fix UUID generation

.github/workflows/deploy.yml, .github/workflows/sonarcloud.yml
Fixed the sonarcloud and renamed the build name
=> Config Into Development

backend/src/main/java/tech/geocodeapp/geocode/Collectable/Controller/CollectableApi.java, backend/src/main/java/tech/geocodeapp/geocode/Collectable/Controller/CollectableApiController.java
Fixed the naming of the API call in the controller to match other references to it.
=> Refactored getCollectableTypeBySet to be called getCollectableTypesBySet

backend/src/main/java/tech/geocodeapp/geocode/User/Service/UserServiceImpl.java
PR to try remove swapCollectable use case for User
=> removing unused imports

backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Model/GeoCode.java, backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Request/CreateGeoCodeRequest.java, backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Request/SwapCollectablesRequest.java, backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Response/GetHintsResponse.java, backend/src/main/java/tech/geocodeapp/geocode/GeoCode/Service/GeoCodeServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/GeoCode/GeoCodeServiceImplTest.java
Cleaned the code imports up a little
=> GeoCode removed unused imports

backend/src/main/java/tech/geocodeapp/geocode/collectable/manager/CollectableTypeManager.java
Added a method in CollectableTypeManager to convert a CollectableTypeComponent to a CollectableType to allow use of the base CollectableType by other backend subsystems.
=> Added method to convert CollectableTypeComponents to CollectableTypes

backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableServiceImplIT.java
Fix id's in valid integration tests so they actually are valid ID's
=> Add correct ID's to Valid Tests

README.md, backend/src/main/java/tech/geocodeapp/geocode/appglobal/security/NewUserInterceptor.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/request/GetCollectableByIDRequest.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/request/GetCollectableTypeByIDRequest.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/response/GetCollectableByIDResponse.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/response/GetCollectableTypeByIDResponse.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/service/CollectableService.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/service/CollectableServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/controller/GeoCodeApi.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/controller/GeoCodeApiController.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/model/GeoCode.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeService.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/user/model/User.java, backend/src/main/java/tech/geocodeapp/geocode/user/request/GetFoundCollectableTypesRequest.java, backend/src/main/java/tech/geocodeapp/geocode/user/request/GetFoundGeoCodesRequest.java, backend/src/main/java/tech/geocodeapp/geocode/user/request/GetOwnedGeoCodesRequest.java, backend/src/main/java/tech/geocodeapp/geocode/user/request/SwapCollectableRequest.java, backend/src/main/java/tech/geocodeapp/geocode/user/response/GetCurrentCollectableResponse.java, backend/src/main/java/tech/geocodeapp/geocode/user/response/GetFoundGeoCodesResponse.java, backend/src/main/java/tech/geocodeapp/geocode/user/response/GetOwnedGeoCodesResponse.java, backend/src/main/java/tech/geocodeapp/geocode/user/response/SwapCollectableResponse.java, backend/src/main/java/tech/geocodeapp/geocode/user/service/UserService.java, backend/src/main/java/tech/geocodeapp/geocode/user/service/UserServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplTest.java
Added new checks to ensure the user who created the GeoCode can't swap collectables
=> Updated the GeoCode subsystem

backend/src/main/java/tech/geocodeapp/geocode/user/controller/UserApi.java
added User/getCurrentCollectable back to UserApi
=> added User/getCurrentCollectable back to UserApi

frontend/src/theme/variables.scss
Updated and improved colour scheme for application to be more subtle
=> Created new colours for colour scheme for both light and dark mode

frontend/src/app/tabs/events/event-timetrial/event-timetrial.page.ts
Fixed the issue that causes maps tests to fail
=> Changed google maps to use library

backend/src/main/java/tech/geocodeapp/geocode/event/request/GetEventByIDRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/response/GetEventByIDResponse.java, backend/src/main/java/tech/geocodeapp/geocode/event/service/EventService.java, backend/src/main/java/tech/geocodeapp/geocode/event/service/EventServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/model/Difficulty.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/model/GeoCode.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/request/CreateGeoCodeRequest.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/request/GetGeoCodeByIDRequest.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/response/GetGeoCodeByIDResponse.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeService.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/repository/PointRepository.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/request/GetEventLeaderboardRequest.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/request/GetPointForUserRequest.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/request/UpdatePointRequest.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/response/GetPointForUserResponse.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/service/LeaderboardService.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/service/LeaderboardServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/user/request/SwapCollectableRequest.java, backend/src/main/java/tech/geocodeapp/geocode/user/service/UserServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/leaderboard/LeaderboardServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/leaderboard/PointMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplTest.java
All required unit tests for getEventLeaderboard
=> Unit tests for getEventLeaderboard

backend/src/main/java/tech/geocodeapp/geocode/event/service/EventServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeService.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java
=> Save event ids in geocodes on event creation

backend/src/main/java/tech/geocodeapp/geocode/event/controller/EventApi.java, backend/src/main/java/tech/geocodeapp/geocode/event/controller/EventApiController.java, backend/src/main/java/tech/geocodeapp/geocode/event/repository/LevelRepository.java, backend/src/main/java/tech/geocodeapp/geocode/event/request/CreateEventRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/request/EventsNearMeRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/service/EventServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/event/EventServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/event/LevelMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java
- Add LevelRepository to store levels
- Add getAllEvents to controller 
- Add getEventsNearMe to controller
=> Make Leaderboard functions usable on frontend

backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java
Updated how the collectable type was fetched when creating a collectable to put into a new GeoCode
=> Made fetching collectable type dynamic

backend/src/main/java/tech/geocodeapp/geocode/event/controller/EventApi.java, backend/src/main/java/tech/geocodeapp/geocode/event/controller/EventApiController.java, backend/src/main/java/tech/geocodeapp/geocode/event/service/EventServiceImpl.java
- Add getEvent to controller
- Update nextStage to save levels, and automatically call it if user is not in an event
=> Updates to Event subsystem

backend/src/main/java/tech/geocodeapp/geocode/leaderboard/service/LeaderboardService.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/service/LeaderboardServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/leaderboard/LeaderboardServiceImplTest.java
Created a method for saving a Point for use in other backend subsystems.
=> Created savePoint method

backend/src/main/java/tech/geocodeapp/geocode/collectable/service/CollectableServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/general/RFC3339DateFormat.java, backend/src/main/java/tech/geocodeapp/geocode/general/api/ApiException.java, backend/src/main/java/tech/geocodeapp/geocode/general/api/ApiOriginFilter.java, backend/src/main/java/tech/geocodeapp/geocode/general/api/ApiResponseMessage.java, backend/src/main/java/tech/geocodeapp/geocode/general/api/NotFoundException.java, backend/src/main/java/tech/geocodeapp/geocode/general/security/KeycloakSecurityConfig.java, backend/src/main/java/tech/geocodeapp/geocode/general/security/NewUserInterceptor.java, backend/src/main/java/tech/geocodeapp/geocode/general/swaggerui/CustomInstantDeserializer.java, backend/src/main/java/tech/geocodeapp/geocode/general/swaggerui/HomeController.java, backend/src/main/java/tech/geocodeapp/geocode/general/swaggerui/JacksonConfiguration.java, backend/src/main/java/tech/geocodeapp/geocode/general/swaggerui/SwaggerDocumentationConfig.java, backend/src/main/java/tech/geocodeapp/geocode/general/swaggerui/SwaggerUiConfiguration.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/controller/LeaderboardApi.java, backend/src/main/java/tech/geocodeapp/geocode/mission/controller/MissionApi.java, backend/src/main/java/tech/geocodeapp/geocode/user/service/UserServiceImpl.java, backend/src/main/resources/application.properties, backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableSetMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableTypeMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplTest.java, backend/src/test/resources/application.properties
- Set user trackable IDs to 00000000-0000-0000-0000-000000000000
- Add CORS to leaderboard and mission controllers
- Automatically create User Trackable sets/types on startup
- Move appglobal files to general
- RegisterNewUser checks more efficiently
=> Various updates to User

backend/src/main/java/tech/geocodeapp/geocode/collectable/request/CreateCollectableRequest.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/response/CollectableResponse.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/service/CollectableServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/mission/service/MissionServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/mission/MissionServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplTest.java
Added code to create a mission for a collectable if the mission flag is set and updated the request and response objects for createCollectable.
=> Added code to create missions

backend/src/main/java/tech/geocodeapp/geocode/collectable/decorator/CollectableTypeComponent.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/decorator/CollectableTypeDecorator.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/decorator/ConcreteCollectableType.java, backend/src/main/java/tech/geocodeapp/geocode/collectable/manager/CollectableTypeManager.java
Added conversion for missionType in the collectableManager and the decorator pattern.
=> Added missionType to the collectableManager

backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java
Added the use case UpdateGeocdoe
=> Added Update GeoCode use case

backend/src/main/java/tech/geocodeapp/geocode/geocode/request/UpdateGeoCodeRequest.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java, backend/src/test/java/tech/geocodeapp/geocode/collectable/CollectableTypeMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeServiceImplTest.java
Made the update GeoCode attributes more strict.
=> Improved UpdateGeoCode

backend/src/main/java/tech/geocodeapp/geocode/event/blockly/Block.java, backend/src/main/java/tech/geocodeapp/geocode/event/blockly/TestCase.java, backend/src/main/java/tech/geocodeapp/geocode/event/decorator/BlocklyEventDecorator.java, backend/src/main/java/tech/geocodeapp/geocode/event/decorator/ConcreteEvent.java, backend/src/main/java/tech/geocodeapp/geocode/event/factory/BlocklyEventFactory.java, backend/src/main/java/tech/geocodeapp/geocode/event/manager/EventManager.java, backend/src/main/java/tech/geocodeapp/geocode/event/model/Event.java, backend/src/main/java/tech/geocodeapp/geocode/event/request/CheckOutputRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/request/GetBlocksRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/request/GetEventDetailsByIDRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/request/GetInputsRequest.java, backend/src/main/java/tech/geocodeapp/geocode/event/service/EventServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/general/CheckNullRequestParameters.java, backend/src/main/java/tech/geocodeapp/geocode/geocode/service/GeoCodeServiceImpl.java, backend/src/main/java/tech/geocodeapp/geocode/leaderboard/controller/LeaderboardApiController.java, backend/src/test/java/tech/geocodeapp/geocode/event/EventServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/event/EventServiceImplTest.java, backend/src/test/java/tech/geocodeapp/geocode/event/GeoCodeMockService.java, backend/src/test/java/tech/geocodeapp/geocode/event/blockly/blocks/too_few_blocks.json, backend/src/test/java/tech/geocodeapp/geocode/event/blockly/blocks/valid1.json, backend/src/test/java/tech/geocodeapp/geocode/event/blockly/testCases/inconsistent_num_inputs.json, backend/src/test/java/tech/geocodeapp/geocode/event/blockly/testCases/valid1.json, backend/src/test/java/tech/geocodeapp/geocode/geocode/GeoCodeMockRepository.java, backend/src/test/java/tech/geocodeapp/geocode/leaderboard/UserMockService.java, backend/src/test/java/tech/geocodeapp/geocode/user/MockSecurity.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplIT.java, backend/src/test/java/tech/geocodeapp/geocode/user/UserServiceImplTest.java
Testing for blockly and related changes.
=> Testing for blockly

.github/workflows/maven-integration-tests-2.yml, .github/workflows/maven-integration-tests-standalone.yml, .github/workflows/maven-integration-tests.yml
This doesn't replace the existing integration testing (for now) but might in the future if we can get it to work as well as the existing setup.
=> Try using a standalone DB running inside Actions for integration testing
